### ISSUE TITLE
can not compile success in centos8 gcc-g++8.3.1 20191121

### ISSUE THREAD

**Issue by SisMaker** [ChomperT/simdjson_erlang#1]
1. in the c_src/simdjson_nif.cpp need add #include<unorderd_map>
2. after otp23 the erl_interface not support, so in the c_src Makefile flag LDLIBs -lerl_interface need delete

**Comment by SisMaker** [comment]
it's like have other problem, compile got the *.so is "simdjson_erlang.so"， but the simdjson.erl load so file name is "simdjon".
the other quest some test show the decode not fast than the jiffy decode , also the same json nif.

**Comment by ChomperT** [comment]
Fixed, thank you!
